# STACKS: [db2, mts, oracle, oracle12c, php54, php55, php56, phpenv, qa-php53, qa-php54, ubuntu-driver]
ACTIVE_STACK: php54
STACKS:
  php54:
    cpus: 2
    ssd: false
    memory: 2048
    share:
      -
       source: "~/stack_php54/log"
       target: "/var/log/httpd"
      -
       source: "~/stack_php54/conf.d"
       target: "/etc/httpd/conf.d"
  oracle12c:
    cpus: 2
    ssd: false
    memory: 3072
    forward_agent: true
    forward_port: true
    forwarded_port:
      80: 8080
      3333: 8333
      3334: 8334
      9200: 8920
      9000: 9900
      9191: 9191
      1521: 1521
    puppet:
      options: "--verbose"
    share:
      -
       source: "~/stack_oracle12c/log"
       target: "/var/log/httpd"
      -
       source: "~/stack_oracle12c/conf.d"
       target: "/etc/httpd/conf.d"
  php55:
    cpus: 2
    ssd: true
    memory: 1512
    video_memory: 12
    forward_agent: true
    forward_port: true
    forwarded_port:
      80: 8580
    share:
      -
       source: "~/stack_php55/log"
       target: "/var/log/httpd"
      -
       source: "~/stack_php55/conf.d"
       target: "/etc/httpd/conf.d"